services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
  sso-service:
    build: ./sso-service
    environment:
      CONFIG_PATH: "/app/config/dev.yml"
    ports:
      - "9090:9090"
      - "7070:7070"
    depends_on:
      db:
        condition: service_healthy
  front:
    build: ./front
    ports:
      - 3000:3000
volumes:
  pgdata: