package postgresql

import (
	"database/sql"
	"fmt"

	_ "github.com/lib/pq"
)

type Storage struct {
	db *sql.DB
}

func New(connStr string) (*Storage, error) {
	const op = "storage.postgresql.New"

	var db *sql.DB
	var err error

	db, err = sql.Open("postgres", connStr)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	if _, err := db.Exec(`
        CREATE TABLE IF NOT EXISTS users(
            id     INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            status TEXT NOT NULL
        );
    `); err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	return &Storage{db: db}, nil
}
