env: "dev" # local/dev/prod
storage_path: "host=db port=5432 user=admin password=admin dbname=postgres sslmode=disable"
token_ttl: 
grpc:
  timeout: 30s
  port: 9090
smtp:
  host: "smtp.yandex.ru"
  addr: "smtp.yandex.ru:587"
  sender: "ivan.onetwozzz.plus@ya.ru"
  username: "ivan.onetwozzz.plus@ya.ru"
  password: "zuifqtpczqccgybg"