env: "local" # local/dev/prod
storage_path: "host=localhost port=5432 user=admin password=admin dbname=postgres sslmode=disable"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s